### ISSUE TITLE
brew install vrui generating errors

### ISSUE THREAD

**Issue by jkopera** [KeckCAVES/homebrew-keckcaves#1]
Error output:

==> Cloning https://github.com/KeckCAVES/Vrui.git
Updating /Library/Caches/Homebrew/vrui--git
==> Checking out revision v2.7-001
==> make INSTALLDIR=/usr/local/Cellar/vrui/2.7-001-1 DOCINSTALLDIR=/usr/local/Cell
Comm/TCPPipe.cpp:198:15: error: no member named 'pselect' in namespace 'Misc'
        return Misc::pselect(&readFds,0,0,timeout)>=0&&readFds.isSet(fd);
               ~~~~~~^
2 errors generated.
make: **\* [o/g++-3.g0.O3/Comm/TCPPipe.o] Error 1

Can't install lidar viewer and vrui-examples due to vrui dependency.

**Comment by Ylannl** [comment]
That issue has been solved: https://github.com/KeckCAVES/Vrui/issues/2

**Comment by melanopsis** [comment]
Please run "brew update" and try to install again.
